version: '3.9'

services:
  link-shortener:
    build:
      dockerfile: Dockerfile
      target: prod
      context: .
    depends_on:
      - redis
    expose:
      - "8080:8080"
  redis:
    image: redis
    expose:
      - "6379:6379"
  tests:
    image: maven:latest
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.m2:/root/.m2
    command: mvn test